export type StreamArgs = {
  name: string,
  stream: string,
  network: string,
  social_distance: boolean,
  cuda: boolean,
  input_fps: string,
  output_fps: string,
  output_scale_factor: string,
  model: string,
  bias: string,
  show_heatmap: boolean,
  object_threshold: string,
  non_max_suppression: string,
  sliding_window: string,
  callback_urls: string,
  selected_gpu: number | null,
  save_images: boolean,
  scale_factor: number,
  roi_id: string,
  loi_id: string,
}

export default {
  name: '',
  stream: '',
  network: '',
  social_distance: false,
  cuda: true,
  input_fps: '',
  output_fps: '',
  output_scale_factor: '',
  model: '',
  bias: '',
  show_heatmap: false,
  object_threshold: '',
  non_max_suppression: '',
  sliding_window: '',
  callback_urls: '',
  selected_gpu: null,
  save_images: false,
  scale_factor: 1.0,
  roi_id: '',
  loi_id: '',
} as StreamArgs
