const UserRoute = require('./UserRoute')
const StaticFilesRoute = require('./StaticFilesRoute')
const FramesRoute = require('./FramesRoute')
const JobsRoute = require('./JobsRoute')
const CollectionsRoute = require('./CollectionsRoute')
const DatasetsRoute = require('./DatasetsRoute')
const TrainingRunsRoute = require('./TrainingRunsRoute')
const NeuralNetworkRoute = require('./NeuralNetworkRoute')
const StreamInstanceRoute = require('./StreamInstanceRoute')
const StreamCaptureRoute  = require('./StreamCaptureRoute')
const GpuRoute = require('./GpuRoute')
const WebsocketRoute = require('./WebsocketRoute')
const DebugRoute = require('./DebugRoute')
const MultiCaptureRoute = require('./MultiCaptureRoute')
const CameraRoute = require('./CameraRoute')
const DeployRoute = require('./DeployRoute')

module.exports = (app, deps) => {
  console.log('mount routes with deps', deps)

  app.use('/users', UserRoute(deps))
  app.use('/files', StaticFilesRoute(deps))
  app.use('/frames', FramesRoute(deps))
  app.use('/jobs', JobsRoute(deps))
  app.use('/collections', CollectionsRoute(deps))
  app.use('/datasets', DatasetsRoute(deps))
  app.use('/training_runs', TrainingRunsRoute(deps))
  app.use('/neural_networks', NeuralNetworkRoute(deps))
  app.use('/stream_instance', StreamInstanceRoute(deps))
  app.use('/stream_capture', StreamCaptureRoute(deps))
  app.use('/gpu', GpuRoute(deps))
  app.use('/websocket', WebsocketRoute(deps))
  app.use('/debug', DebugRoute(deps))
  app.use('/multicapture_stream', MultiCaptureRoute(deps))
  app.use('/cameras', CameraRoute(deps))
  app.use('/deploys', DeployRoute(deps))
}
