# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend Test

on:
  pull_request:
    types: [opened, closed, synchronize, labeled, unlabeled]
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
#     - run: pwd
    - run: yarn install
      working-directory: frontend
      env: 
        EAGLE_EYE_PATH: /home/runner/work/public-eye/public-eye
    - run: yarn run test
      working-directory: frontend
      env: 
        EAGLE_EYE_PATH: /home/runner/work/public-eye/public-eye
